version: "3.7"

services:
  database_emidio:
    image: postgres
    container_name: database_emidio
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=emidio
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: emidio
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
